version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Packaging Lambda functions"
      - mkdir -p build
      # Package each Lambda directory into its own zip
      - cd lambdas
      - for f in */ ; do
          name=$(basename "$f");
          echo "Zipping $name";
          cd "$name";
          pip install -r requirements.txt -t .;
          zip -r "../../build/${name}.zip" .;
          cd ..;
        done
artifacts:
  files:
    - build/*
