version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade awscli

  build:
    commands:
      - set -e
      - ARTIFACT_DIR=${ARTIFACT_DIR:-artifacts}
      - INDEX_ZIP="$ARTIFACT_DIR/index-photos.zip"
      - SEARCH_ZIP="$ARTIFACT_DIR/search-photos.zip"
      - INDEX_LAMBDA_NAME=${INDEX_LAMBDA_NAME:-index-photos-lf1}
      - SEARCH_LAMBDA_NAME=${SEARCH_LAMBDA_NAME:-search-photos-l2}
      - REGION=${AWS_REGION:-us-east-1}

      - echo "Creating artifacts directory"
      - mkdir -p "$ARTIFACT_DIR"
      
      # Build index-photos Lambda
      - echo "Building upload_photos Lambda"
      - cd lambdas/upload_photos
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - zip -r "../../$INDEX_ZIP" . -x '*.pyc' '__pycache__/*' '*.git/*'
      - cd ../..

      # Build search-photos Lambda
      - echo "Building search_photos Lambda"
      - cd lambdas/search_photos
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - zip -r "../../$SEARCH_ZIP" . -x '*.pyc' '__pycache__/*' '*.git/*'
      - cd ../..

      # Verify zips exist
      - test -f "$INDEX_ZIP" && echo "✓ $INDEX_ZIP created"
      - test -f "$SEARCH_ZIP" && echo "✓ $SEARCH_ZIP created"

      # Deploy to Lambda
      - echo "Deploying $INDEX_LAMBDA_NAME"
      - aws lambda update-function-code --function-name "$INDEX_LAMBDA_NAME" --zip-file fileb://"$INDEX_ZIP" --region "$REGION"
      
      - echo "Deploying $SEARCH_LAMBDA_NAME"
      - aws lambda update-function-code --function-name "$SEARCH_LAMBDA_NAME" --zip-file fileb://"$SEARCH_ZIP" --region "$REGION"
      
      - echo "✓ Both Lambdas deployed successfully"

artifacts:
  files: []
