AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for Photo Album Application - Lambda and Frontend Deployment'

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: 'ReKog'

  GitHubOwner:
    Type: String
    Description: GitHub repository owner/organization
    Default: 'dropsaurus'

  GitHubBranch:
    Type: String
    Description: GitHub branch to track
    Default: 'main'

  GitHubToken:
    Type: String
    Description: GitHub personal access token (needs repo scope)
    NoEcho: true

Resources:
  # ============================================
  # S3 Bucket for CodePipeline Artifacts
  # ============================================

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'photo-album-pipeline-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30

  # ============================================
  # IAM Roles for CodePipeline and CodeBuild
  # ============================================

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CodePipeline-S3Deploy-us-east-1-P2-Frontend-Pipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:GetObjectVersion'
                Resource: !Sub '${ArtifactBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !GetAtt ArtifactBucket.Arn
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: !Sub '${ArtifactBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - 'lambda:UpdateFunctionCode'
                  - 'lambda:GetFunction'
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:index-photos-lf1'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:search-photos-l2'
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub 'arn:aws:s3:::roshan-assignment3-frontend-b1-${AWS::AccountId}/*'
                  - !Sub 'arn:aws:s3:::roshan-assignment3-frontend-b1-${AWS::AccountId}'

  # ============================================
  # CodeBuild Projects
  # ============================================

  LambdaBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: PhotoAlbum-Lambda-Build
      Description: Build and deploy Lambda functions for photo album
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml
      TimeoutInMinutes: 15

  FrontendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: PhotoAlbum-Frontend-Build
      Description: Deploy frontend for photo album
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-frontend.yaml
      TimeoutInMinutes: 10

  # ============================================
  # CodePipeline P1 - Lambda Functions
  # ============================================

  LambdaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: LambdaPipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref BuildLambdas
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput

  # ============================================
  # CodePipeline P2 - Frontend
  # ============================================

  FrontendPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: P2-Frontend-Pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref frontend-build
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DeployOutput

Outputs:
  LambdaPipelineName:
    Description: Lambda deployment pipeline name
    Value: !Ref LambdaPipeline

  FrontendPipelineName:
    Description: Frontend deployment pipeline name
    Value: !Ref P2-Frontend-Pipeline

  ArtifactBucketName:
    Description: S3 bucket for pipeline artifacts
    Value: !Ref ArtifactBucket

  LambdaPipelineURL:
    Description: URL to Lambda pipeline in console
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${LambdaPipeline}/view'

  FrontendPipelineURL:
    Description: URL to Frontend pipeline in console
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${FrontendPipeline}/view'
