AWSTemplateFormatVersion: '2010-09-09'
Description: 'Photo Album Application - Minimal CloudFormation Template'

Parameters:
  OpenSearchEndpoint:
    Type: String
    Description: OpenSearch domain endpoint (created manually)
    Default: 'search-photos-xxxxx.us-east-1.es.amazonaws.com'

  LexBotId:
    Type: String
    Description: Lex Bot ID (created manually)
    Default: 'XXXXX'

  LexBotAliasId:
    Type: String
    Description: Lex Bot Alias ID (created manually)
    Default: 'TSTALIASID'

Resources:
  # ============================================
  # S3 Buckets
  # ============================================

  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'roshan-assignment3-b2'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [GET, PUT]
            AllowedHeaders: ['*']
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put        
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg               
            Function: !GetAtt IndexPhotosFunction.Arn

  PhotosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PhotosBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${PhotosBucket.Arn}/*'

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'roshan-assignment3-frontend-b1'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # ============================================
  # IAM Roles
  # ============================================

  IndexPhotosRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: indexPhotosPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:HeadObject'
                  - 's3:GetObjectTagging'
                Resource: !Sub '${PhotosBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - 'rekognition:DetectLabels'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'es:ESHttpPost'
                  - 'es:ESHttpPut'
                  - 'es:ESHttpGet'
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/photos/*'

  SearchPhotosRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SearchPhotosPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttpGet'
                  - 'es:ESHttpPost'
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/photos/*'
              - Effect: Allow
                Action:
                  - 'lex:RecognizeText'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                Resource: !Sub 'arn:aws:s3:::${PhotosBucket}/*'

  # ============================================
  # Lambda Functions
  # ============================================

  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos-lf1
      Runtime: python3.14
      Handler: lambda_function.lambda_handler
      Role: !GetAtt IndexPhotosRole.Arn
      Timeout: 30
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref OpenSearchEndpoint
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Placeholder - deploy actual code')}

  IndexPhotosPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IndexPhotosFunction
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt PhotosBucket.Arn

  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos
      Runtime: python3.14
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SearchPhotosRole.Arn
      Timeout: 15
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref OpenSearchEndpoint
          LEX_BOT_NAME: !Ref LexBotId
          LEX_BOT_ALIAS: !Ref LexBotAliasId
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps({'results': []})}

  # ============================================
  # API Gateway
  # ============================================

  PhotoAlbumAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PhotoAlbumAPI
      Description: Photo Album API with search and upload

  # API Key
  APIKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: APIDeployment
    Properties:
      Name: PhotoAlbumAPIKey
      Enabled: true
      StageKeys:
        - RestApiId: !Ref PhotoAlbumAPI
          StageName: testing

  # Usage Plan
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: APIDeployment
    Properties:
      UsagePlanName: BasicPlan
      ApiStages:
        - ApiId: !Ref PhotoAlbumAPI
          Stage: prod
      Throttle:
        RateLimit: 10
        BurstLimit: 2
      Quota:
        Limit: 10000
        Period: MONTH

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref APIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # GET /search
  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !GetAtt PhotoAlbumAPI.RootResourceId
      PathPart: search

  SearchMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  SearchMethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref SearchResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  SearchLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SearchPhotosFunction
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoAlbumAPI}/*'

  # PUT /photos/{filename}
  PhotosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !GetAtt PhotoAlbumAPI.RootResourceId
      PathPart: photos

  PhotosFilenameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !Ref PhotosResource
      PathPart: '{filename}'

  PhotosPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref PhotosFilenameResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.filename: true
        method.request.header.x-amz-meta-customLabels: false
      Integration:
        Type: AWS
        IntegrationHttpMethod: PUT
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:s3:path/${PhotosBucket}/{filename}'
        Credentials: !GetAtt APIGatewayS3Role.Arn
        RequestParameters:
          integration.request.path.filename: method.request.path.filename
          integration.request.header.x-amz-meta-customLabels: method.request.header.x-amz-meta-customLabels
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  PhotosOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref PhotosFilenameResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  APIGatewayS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3PutObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: !Sub '${PhotosBucket.Arn}/*'

  # Deploy API
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - SearchMethod
      - SearchMethodOptions
      - PhotosPutMethod
      - PhotosOptionsMethod
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      StageName: testing

Outputs:
  FrontendURL:
    Description: Frontend website URL
    Value: !GetAtt FrontendBucket.WebsiteURL

  APIEndpoint:
    Description: API Gateway endpoint
    Value: !Sub 'https://${PhotoAlbumAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'

  APIKeyId:
    Description: API Key ID (retrieve value from console)
    Value: !Ref APIKey

  PhotosBucketName:
    Description: Photos storage bucket
    Value: !Ref PhotosBucket

  FrontendBucketName:
    Description: Frontend bucket
    Value: !Ref FrontendBucket
